import {TextEdit, Button} from "std-widgets.slint";

export component App inherits Window {
    in-out property <string> current <=> editor.text;
    in property <image> display <=> viewer.source;

    in-out property <int> current_page: 0;

    callback compile();
    callback next();
    callback prev();



    title: "Fiber Editor";
    preferred-width: 1440px;
    preferred-height: 844px;

    VerticalLayout {
    	spacing: 5px;
   		HorizontalLayout {
     		width: 100%;
       		height: 30px;

         	spacing: 3px;


   			Button {
   				width: 150px;
    			text: "Previous page";
    			clicked => {
   					root.prev();
        			editor.clear-focus();
       			}
      		}
        	Button {
         		width: 150px;
      			text: "Next page";
      			clicked => {
      				root.next();
          			editor.clear-focus();
             	}
            }
           	Rectangle {
            	width: 150px;
            	background: green;
            	border-bottom-left-radius: 10px;
            	border-bottom-right-radius: 10px;
            	border-top-left-radius: 10px;
            	border-top-right-radius: 10px;

            	TouchArea {
           			Text {
              	 		text: "Compile";
                  	}

	            	clicked => {
	           			root.compile();
	              		editor.clear-focus();
	             	}
              	}
            }

     	}

	    HorizontalLayout {
			spacing: 3px;
	        editor := TextEdit {
	            width: 60%;
	            text: "\\documentclass{article}\n\\usepackage{graphicx} % Required for inserting images\n\\title{test}\n\\author{Aiden Ghim}\n\\date{October 2025}\n\\begin{document}\n\n\\maketitle\n\n\\section{Introduction}\n\\end{document}";

				font-size: 16px;

	            edited => {
	                root.current = self.text;
	            }
	        }

	        viewer := Image {
		        width: 40%;
	        }

	    }
	}
}
