import {TextEdit, Button} from "std-widgets.slint";

export component App inherits Window {
    in-out property <string> current <=> editor.text;
    in property <image> display <=> viewer.source;

    in-out property <int> current_page: 0;

    callback compile();
    callback next();
    callback prev();
    callback download();



    title: "Fiber Editor";
    preferred-width: 1440px;
    preferred-height: 844px;

    VerticalLayout {
    	spacing: 5px;
   		HorizontalLayout {
     		width: 100%;
       		height: 30px;

         	spacing: 3px;

          	Button {
           		width: 100px;
             	text: "Download";
              	clicked => {root.download();}
           	}

         	Rectangle {
         		Text {
          			text: "Fiber Editor for LaTeX";
            	}
          	}

   			Button {
   				width: 150px;
    			text: "Previous page";
    			clicked => {
   					root.prev();
        			editor.clear-focus();
       			}
      		}
        	Button {
         		width: 150px;
      			text: "Next page";

      			clicked => {
      				root.next();
          			editor.clear-focus();
             	}
            }
           	Rectangle {
            	width: 150px;
            	background: green;
            	border-bottom-left-radius: 10px;
            	border-bottom-right-radius: 10px;
            	border-top-left-radius: 10px;
            	border-top-right-radius: 10px;



            	TouchArea {
           			mouse-cursor: pointer;
           			Text {
              	 		text: "Compile";
                  	}

	            	clicked => {
						editor.clear-focus();

	           			root.compile();
	             	}
              	}
            }

     	}

	    HorizontalLayout {
			spacing: 3px;
	        editor := TextEdit {
	            width: 55%;
	            text: "\\documentclass{article}\n\\usepackage{graphicx} % Required for inserting images\n\\title{Title of Document}\n\\author{Name of Author}\n\\date{Month Year}\n\\begin{document}\n\n\\maketitle\n\n\\section{Introduction}\n\\end{document}";

				font-size: 15pt;


	            edited => {
	                root.current = self.text;
	            }
	        }

	        viewer := Image {
		        width: 45%;
	        }

	    }
	}
}
