import {TextEdit, Button} from "std-widgets.slint";

export component App inherits Window {
    in-out property <string> current <=> editor.text;
    in property <image> display <=> viewer.source;

    in-out property <int> current_page: 0;

    callback compile();
    callback next();
    callback prev();



    title: "Fiber Editor";
    preferred-width: 1440px;
    preferred-height: 844px;

    VerticalLayout {
   		HorizontalLayout {
     		Text {
       			text: "Viewing page " + current_page;
       		}
   			Button {
    			text: "Previous page";
    			clicked => {
       				if current_page > 0 {
       					current_page = current_page - 1;
           			}
       			}
      		}
        	Button {
      			text: "Next page";
      			clicked => {
         			current_page = current_page + 1;
             	}
            }
           	Button {
            	text: "Compile";
            	clicked => {
           			root.compile();
             	}
            }

     	}

	    HorizontalLayout {
	        editor := TextEdit {

	            width: 40%;
	            height: 80%;

	            text: "\\documentclass{article}\n\\usepackage{graphicx} % Required for inserting images\n\\title{test}\n\\author{Aiden Ghim}\n\\date{October 2025}\n\\begin{document}\n\n\\maketitle\n\n\\section{Introduction}\n\\end{document}";

	            edited => {
	                root.current = self.text;
	            }
	        }

	        viewer := Image {
		        width: 40%;
		        height: 80%;
	        }

	    }
	}
}
